### ISSUE TITLE
Khởi tạo backend project cho hệ thống eic-document

### ISSUE THREAD

**Issue by thanhtdvn** [easywebhub/tasks#72]
> Dựa theo https://github.com/vinaas/tasks/issues/1

* [x] Khởi tạo project: .net core api connect couchbase db https://github.com/easywebhub/eic-document-system/issues/1
* [ ] Tích hợp hệ thống chứng thực IdentiyServer (https://github.com/easywebhub/NetCoreIdentityServer)  https://github.com/easywebhub/eic-document-system/issues/4
* [ ] Xây dựng các thực thể liên quan module Nhân Viên, Phòng ban https://github.com/easywebhub/eic-document-system/issues/2
* [ ] Cung cấp API cho các module Quản lý Nhân viên, Phòng ban https://github.com/easywebhub/eic-document-system/issues/3

**Comment by baotnq** [comment]
cái này tới đâu rồi em, có gì cập nhật trạng thái, cũng như commit code nghe
