### ISSUE TITLE
Review EasyBuilder

### ISSUE THREAD

**Issue by baotnq** [easywebhub/tasks#81]
### todo
- review easyweb skeleton https://github.com/easywebhub/easymarket, 
  - [x] there're many errors when loading with EasyBuilder (Debug.bat)
  - [x] remove pre-compiler process, such as `sass build`, to improve speed of building process of this skeleton

- review the F1, F2, F3
  - [x] F2 could not insert fields, 
  - [ ] F2: option to create objects, then insert fields 
  - [ ] F1 not refresh 
- review the Asset, 
  - [x] wrong related file-path of asset files, remote `/asset` at beginning
  - [ ] add editor for css, js files 

- add inline editing to EasyBuilder, 
  - [ ] decide to adding `Inline` tab beside the `Open on browser` or beside the `Form` ?

**Comment by baotnq** [comment]
@nemesisqp bổ sung thêm tính năng cho F2 nghe, anh note ở trên.
